codecov:
  branch: dev
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      pg_bm25:
        flags: pg_bm25
        target: auto
        threshold: 1%
    patch:
      pg_bm25:
        flags: pg_bm25
        target: auto
        threshold: 1%

comment: false

flags:
  pg_bm25:
    paths:
      - pg_bm25/*
    carryforward: true
