version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      update-types: ["version-update:semver-patch"]    
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "monthly"
    ignore:
      update-types: ["version-update:semver-patch"]
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/pg_bm25"
    schedule:
      interval: "monthly"
    ignore:
      update-types: ["version-update:semver-patch"]
    groups:
      dependencies:
        patterns:
          - "*"
