version: "3.9"

services:
  deps:
    image: python:3.9-slim
    volumes:
      - .:/app
      - python-deps:/usr/local/lib/python3.9/site-packages
    working_dir: /app
    command:
      - pip
      - install
      - --no-cache-dir
      - -r
      - /app/requirements.txt

  run-cdc:
    image: python:3.9-slim
    volumes:
      - .:/app
      - python-deps:/usr/local/lib/python3.9/site-packages
    working_dir: /app
    entrypoint:
      - INSERT_HERE

volumes:
  python-deps:
