# This docker-compose.yml file is for a hobby production deploy

version: "3.8"

services:
  paradedb:
    image: retake/paradedb:latest
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
