# This docker-compose.dev.yml file is for local development

version: "3.8"

services:
  paradedb:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        - PG_VERSION_MAJOR=15
        - PG_BM25_VERSION=0.0.0
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - paradedb_data:/var/lib/postgresql/data

volumes:
  paradedb_data:
