#
# This docker-compose.dev.yml file is for development of the ParadeDB extensions only. It
# builds the Dockerfile.dev, which currently only builds pg_bm25 and pgvector, to allow
# for rapid testing of changes to these extensions. It is not intended for production use.
#

version: "3.8"

services:
  paradedb:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
      args:
        PG_VERSION_MAJOR: 15
        PG_BM25_VERSION: 0.0.0
        PGML_VERSION: 2.7.8
        PGVECTOR_VERSION: 0.5.0
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
