# Postgres symbols won't be available until runtime

[target.'cfg(target_os="macos")']
rustflags = ["-Clink-arg=-Wl,-undefined,dynamic_lookup","-Cinstrument-coverage"]

[target.'cfg(not(target_os="macos"))']
rustflags = ["-Cinstrument-coverage"]
