# workflows/lint-rust.yml
#
# Rust: Linting
# Lint Rust files using Clippy and Rustfmt.

name: Linting

on:
  pull_request:
    paths:
      - "**/*.rs"
      - ".github/workflows/lint-rust.yml"
  workflow_dispatch:

concurrency:
  group: lint-rust-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-rust:
    name: Lint Rust
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy,rustfmt

      - name: Install All Supported PostgreSQL Versions
        run: |
          # Install the public key for the repository
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

          # Add the repository
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

          # Update the package list
          sudo apt-get update

          # Install PostgreSQL 11, 12, 13, 14, and 15
          sudo apt-get install -y postgresql-11 postgresql-12 postgresql-13 postgresql-14 postgresql-15
          sudo apt-get install -y postgresql-server-dev-11 postgresql-server-dev-12 postgresql-server-dev-13 postgresql-server-dev-14 postgresql-server-dev-15

      - name: Install pgrx
        working-directory: pg_bm25
        run: cargo install cargo-pgrx

      - name: Initialize pgrx
        working-directory: pg_bm25
        run: |
          cargo pgrx init \
            --pg11=/usr/lib/postgresql/11/bin/pg_config \
            --pg12=/usr/lib/postgresql/12/bin/pg_config \
            --pg13=/usr/lib/postgresql/13/bin/pg_config \
            --pg14=/usr/lib/postgresql/14/bin/pg_config \
            --pg15=/usr/lib/postgresql/15/bin/pg_config

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
        with:
          manifest-path: ./pg_bm25/Cargo.toml

      - name: Run Clippy
        working-directory: ./pg_bm25
        run: cargo clippy --all-targets
