# workflows/publish-paradedb-to-dockerhub.yml
#
# ParadeDB: Publish to Docker Hub
# Publish ParadeDB as a Docker image to Docker Hub. This workflow only runs after a GitHub Release gets
# created, which happens once we merge to `main`.

name: Publishing

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: publish-paradedb-to-dockerhub-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  publish-paradedb-to-dockerhub:
    name: Publish ParadeDB to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Retrieve GitHub Tag
        id: version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Configure Docker Hub Metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: paradedb/paradedb
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}

      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            PG_VERSION_MAJOR=15
            PG_BM25_VERSION=${{ steps.version.outputs.version }}}
            PG_CRON_VERSION=1.6.0
            PG_NET_VERSION=0.7.2
            PG_IVM_VERSION=1.5.1
            PG_GRAPHQL_VERSION=1.3.0
            PG_HASHIDS_VERSION=1.2.1
            PG_JSONSCHEMA_VERSION=0.1.4
            PG_REPACK_VERSION=ver_1.4.8
            PG_STAT_MONITOR_VERSION=2.0.1
            PG_HINT_PLAN_VERSION=REL15_1_5_0
            PGML_VERSION=2.7.8
            PGTAP_VERSION=1.3.0
            PGVECTOR_VERSION=0.5.0
            POSTGIS_VERSION=3.4.0
            PGAUDIT_VERSION=1.7.0
            PGROUTING_VERSION=3.5.0
            PGSQL_HTTP_VERSION=1.6.0
            HYPOPG_VERSION=1.4.0
            RUM_VERSION=1.3.13
          platforms: linux/amd64,linux/arm64
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
